version: 0.8.0.{build}

image:
  - macos-mojave
  - Visual Studio 2017
  - Ubuntu2004

platform:
  - x64

# We don't want to build any other branches; just master
branches:
  only:
    - sdl-rework

for:
-
  matrix:
    only: 
      - image: Ubuntu2004
  install:
    - sudo apt-get update
    - sudo apt-get install libsdl2-dev -y
    - sudo apt-get install libsdl2-image-dev -y
    - sudo apt-get install libsdl2-mixer-dev -y
    - sudo apt-get install libsdl2-ttf-dev -y
    - sudo apt-get install libsdl2-gfx-dev -y

-
  matrix:
    only:
      - image: macos-mojave
  install:
    - brew install sdl2{,_image,_mixer,_ttf,_gfx} pkg-config

-
  matrix:
    only:
      - image: Visual Studio 2017
  install:
    # Set the path to include the 64-bit MinGW
    - set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  build_script:
    - go run ./build_script/main.go -b

build_script:
  - go run ./build_script/main.go -b # Build...

after_build:
  - go run ./build_script/main.go -c # ... Then compress.
  

artifacts:
  
  - path: bin\*.tar.gz
    name: "MasterPlan-$(APPVEYOR_BUILD_WORKER_IMAGE)-$(APPVEYOR_BUILD_VERSION)"

  - path: bin\*.zip
    name: "MasterPlan-$(APPVEYOR_BUILD_WORKER_IMAGE)-$(APPVEYOR_BUILD_VERSION)"
